(defun algoritmoseisdigitos (numero)
  (let ((soma 0))
    (dotimes (i 6)
      (let ((digit (mod numero 10)))
        (when (evenp digit)
          (setf soma (+ soma (expt digit 2))))
        (setf numero (floor numero 10))))
    (print soma)))
(algoritmoseisdigitos 123456)
