(defun six-digit-algorithm (n)
  (let ((sum 0))
    (dotimes (i 6)
      (let ((digit (mod n 10)))
        (when (evenp digit)
          (setf sum (+ sum (expt digit 2))))
        (setf n (floor n 10))))
    (print sum)))
(six-digit-algorithm 123456)
