(defun min-sum-algorithm ()
  (let ((min-sum 999))
    (dotimes (num 100 999)
      (let ((temp num) (sum 0))
        (loop while (> temp 0)
              do (incf sum (mod temp 10))
                 (setf temp (floor temp 10)))
        (when (< sum min-sum)
          (setf min-sum sum))))
    (print min-sum)))
(min-sum-algorithm)
