(defun algoritmominimosoma ()
  (let ((somaminima 999))
    (dotimes (num 100 999)
      (let ((temp num) (soma 0))
        (loop while (> temp 0)
              do (incf soma (mod temp 10))
                 (setf temp (floor temp 10)))
        (when (< soma somaminima)
          (setf somaminima soma))))
    (print somaminima)))
(algoritmominimosoma)
